### PR TITLE
Network fix

### PR DESCRIPTION
**Pull request by EreliaCorp**

### CODE REVIEW

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- playground/src/main.cpp:3
     Compound EmiterWidget is not documented.



- playground/src/main.cpp:15
     Member EmiterWidget(const std::wstring &p_name) (function) of class EmiterWidget is not documented.



- playground/src/main.cpp:18
     Member setClient(spk::Network::Client *p_client) (function) of class EmiterWidget is not documented.



- playground/src/main.cpp:19
     Member setServer(spk::Network::Server *p_server) (function) of class EmiterWidget is not documented.

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- playground/src/main.cpp:3
     Compound EmiterWidget is not documented.



- playground/src/main.cpp:15
     Member EmiterWidget(const std::wstring &p_name) (function) of class EmiterWidget is not documented.



- playground/src/main.cpp:18
     Member setClient(spk::Network::Client *p_client) (function) of class EmiterWidget is not documented.



- playground/src/main.cpp:19
     Member setServer(spk::Network::Server *p_server) (function) of class EmiterWidget is not documented.



- includes/network/linux/spk_network_socket.hpp:37
     Member FileDescriptor (typedef) of class spk::Network::Socket is not documented.



- includes/network/linux/spk_network_socket.hpp:70
     Member fileDescriptor() const (function) of class spk::Network::Socket is not documented.

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- playground/src/main.cpp:3
     Compound EmiterWidget is not documented.



- includes/graphics/windows/spk_window.hpp:1
     member 'spk::Singleton<Window>' of class 'Window' cannot be found



- playground/src/main.cpp:15
     Member EmiterWidget(const std::wstring &p_name) (function) of class EmiterWidget is not documented.



- playground/src/main.cpp:18
     Member setClient(spk::Network::Client *p_client) (function) of class EmiterWidget is not documented.



- playground/src/main.cpp:19
     Member setServer(spk::Network::Server *p_server) (function) of class EmiterWidget is not documented.



- includes/network/windows/spk_network_socket.hpp:30
     Member ReadResult (enumeration) of class spk::Network::Socket is not documented.



- includes/network/linux/spk_network_socket.hpp:37
     Member FileDescriptor (typedef) of class spk::Network::Socket is not documented.



- includes/network/windows/spk_network_socket.hpp:38
     Member FileDescriptor (typedef) of class spk::Network::Socket is not documented.



- includes/network/linux/spk_network_socket.hpp:70
     Member fileDescriptor() const (function) of class spk::Network::Socket is not documented.



- includes/network/windows/spk_network_socket.hpp:79
     Member fileDescriptor() const (function) of class spk::Network::Socket is not documented.



- includes/network/windows/spk_network_object.hpp:100
     Member maxFD() (function) of class spk::Network::Object is not documented.



- includes/network/windows/spk_network_object.hpp:101
     Member readingFDs() (function) of class spk::Network::Object is not documented.

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/graphics/windows/spk_window.hpp:1
     member 'spk::Singleton<Window>' of class 'Window' cannot be found



- includes/network/windows/spk_network_socket.hpp:30
     Member ReadResult (enumeration) of class spk::Network::Socket is not documented.



- includes/network/linux/spk_network_socket.hpp:37
     Member FileDescriptor (typedef) of class spk::Network::Socket is not documented.



- includes/network/windows/spk_network_socket.hpp:38
     Member FileDescriptor (typedef) of class spk::Network::Socket is not documented.



- includes/network/linux/spk_network_socket.hpp:70
     Member fileDescriptor() const (function) of class spk::Network::Socket is not documented.



- includes/network/windows/spk_network_socket.hpp:79
     Member fileDescriptor() const (function) of class spk::Network::Socket is not documented.



- includes/network/windows/spk_network_object.hpp:100
     Member maxFD() (function) of class spk::Network::Object is not documented.



- includes/network/windows/spk_network_object.hpp:101
     Member readingFDs() (function) of class spk::Network::Object is not documented.

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/graphics/windows/spk_window.hpp:1
     member 'spk::Singleton<Window>' of class 'Window' cannot be found



- includes/network/windows/spk_network_socket.hpp:30
     Member ReadResult (enumeration) of class spk::Network::Socket is not documented.



- includes/network/linux/spk_network_socket.hpp:98
     Member fileDescriptor() const (function) of class spk::Network::Socket is not documented.



- includes/network/windows/spk_network_socket.hpp:104
     Member fileDescriptor() const (function) of class spk::Network::Socket is not documented.



- includes/network/windows/spk_network_object.hpp:100
     Member maxFD() (function) of class spk::Network::Object is not documented.



- includes/network/windows/spk_network_object.hpp:101
     Member readingFDs() (function) of class spk::Network::Object is not documented.

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/graphics/windows/spk_window.hpp:1
     member 'spk::Singleton<Window>' of class 'Window' cannot be found



- includes/network/windows/spk_network_socket.hpp:26
     Member ReadResult (enumeration) of class spk::Network::Socket is not documented.

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/graphics/windows/spk_window.hpp:1
     member 'spk::Singleton<Window>' of class 'Window' cannot be found



- includes/network/windows/spk_network_socket.hpp:26
     Member ReadResult (enumeration) of class spk::Network::Socket is not documented.

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/graphics/windows/spk_window.hpp:1
     member 'spk::Singleton<Window>' of class 'Window' cannot be found

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/graphics/windows/spk_window.hpp:1
     member 'spk::Singleton<Window>' of class 'Window' cannot be found

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/network/linux/spk_network_socket.hpp:34
     Member SocketError (variable) of class spk::Network::Socket is not documented.

**Review by NotCampeur — APPROVED** [review]

**Pull request merged**
