### PR TITLE
Fixing resize wrong calculation

### PR DESCRIPTION
**Pull request by Hyarius**
Quick fix for the resize wrong implementation

+ Renaming of a badly named file

### CODE REVIEW

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/graphics/viewport/spk_abstract_viewport.hpp:82
     Member needComputation() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:83
     Member compute() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:82
     Member needComputation() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:83
     Member compute() (function) of class spk::AbstractViewport is not documented.

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/graphics/viewport/spk_abstract_viewport.hpp:82
     Member needComputation() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:83
     Member compute() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:82
     Member needComputation() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:83
     Member compute() (function) of class spk::AbstractViewport is not documented.

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/graphics/viewport/spk_abstract_viewport.hpp:77
     Member needComputation() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:78
     Member compute() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:77
     Member needComputation() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:78
     Member compute() (function) of class spk::AbstractViewport is not documented.

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/graphics/viewport/spk_abstract_viewport.hpp:80
     Member needComputation() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:81
     Member compute() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:80
     Member needComputation() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:81
     Member compute() (function) of class spk::AbstractViewport is not documented.

**Comment by EreliaCorp** [comment]
There is a list of documentation error you need to fix before merging this PullRequest :


- includes/graphics/viewport/spk_abstract_viewport.hpp:80
     Member needComputation() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:81
     Member compute() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:80
     Member needComputation() (function) of class spk::AbstractViewport is not documented.



- includes/graphics/viewport/spk_abstract_viewport.hpp:81
     Member compute() (function) of class spk::AbstractViewport is not documented.

**Review by NotCampeur — APPROVED** [review]

**Pull request merged**
